# database setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examplesdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: suman
    password: suman1234
    driver-class-name: com.mysql.cj.jdbc.Driver
