spring:
  datasource:
      url: jdbc:h2:tcp://localhost/~/datajpa
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true

  logging.level:
    p6spy: info
#    org.hibernate.SQL: trace
decorator:
  datasource:
    p6spy:
      enable-logging: true
